#!/bin/sh
[ -f indexpage.txt ] && mv -f indexpage.txt indexpage.txt.bak
[ -f lf_deutsch_def.txt ] && mv -f lf_deutsch_def.txt lf_deutsch_def.txt.bak
#[ -f transindex.html ] && mv -f transindex.html transindex.html.bak
wget -v http://www.linuxfocus.org/Deutsch/indexpage.txt
wget -v  http://www.linuxfocus.org/Deutsch/lf_deutsch_def.txt 
#wget -v http://www.linuxfocus.org/Deutsch/transindex.html
